services:
    ru_strings.case:
        class: Etfostra\RuStringsBundle\Service\RuCase
        arguments:
            - @snc_redis.default
            - @service_container

    ru_strings.ru_strings_extension:
        class: Etfostra\RuStringsBundle\Twig\RuStringsExtension
        arguments: [ @ru_strings.case ]
        tags:
            - { name: twig.extension }
